// <auto-generated />
namespace Terminal.Core.Data.Entities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addedusernametoinvitecode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedusernametoinvitecode));
        
        string IMigrationMetadata.Id
        {
            get { return "201305200800095_Added username to invite code."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
